import pygame

BOTON_ROJO = pygame.event.Event(pygame.USEREVENT)
BOTON_AZUL = pygame.event.Event(pygame.USEREVENT + 1)
MOSTRAR_PUBLICO = pygame.event.Event(pygame.USEREVENT + 2)
MOSTRAR_RESPUESTA_PUBLICO = pygame.event.Event(pygame.USEREVENT + 4)
MOSTRAR_JUGADOR = pygame.event.Event(pygame.USEREVENT + 5)
SIGUIENTE_PREGUNTA = pygame.event.Event(pygame.USEREVENT + 6)
RESPUESTA_GANADA = pygame.event.Event(pygame.USEREVENT + 7)
RESPUESTA_FALLIDA = pygame.event.Event(pygame.USEREVENT + 8)
TIEMPO_AGOTADO = pygame.event.Event(pygame.USEREVENT + 9)
COMODIN_MITAD = pygame.event.Event(pygame.USEREVENT + 10)
COMODIN_SALTEAR_PREGUNTA = pygame.event.Event(pygame.USEREVENT + 11)
COMODIN_NUEVA_PREGUNTA = pygame.event.Event(pygame.USEREVENT + 12)
ACTUALIZAR_PORCENTAJES_RESPUESTAS = pygame.event.Event(pygame.USEREVENT + 13)
COMPARAR_VOTOS = pygame.event.Event(pygame.USEREVENT + 14)
JUEGO_GANADO = pygame.event.Event(pygame.USEREVENT + 15)
ESCONDER_CARTEL_EVENTO = pygame.event.Event(pygame.USEREVENT + 16)
REHINICIAR = pygame.event.Event(pygame.USEREVENT + 17)
NUEVA_PARTIDA = pygame.event.Event(pygame.USEREVENT + 18)
CONTINUAR_PARTIDA = pygame.event.Event(pygame.USEREVENT + 19)
MOSTRAR_MENU = pygame.event.Event(pygame.USEREVENT + 20)
MOSTRAR_MITAD = pygame.event.Event(pygame.USEREVENT + 21)
CAMBIAR_PREGUNTA = pygame.event.Event(pygame.USEREVENT + 22)